# Generated by Django 5.0.7 on 2024-07-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('product', '0002_alter_product_ingredients_alter_product_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='excluded_ingredient',
            field=models.ManyToManyField(blank=True, to='product.ingredient', verbose_name='Исключенные ингредиенты'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='topping',
            field=models.ManyToManyField(blank=True, to='product.topping', verbose_name='Добавки'),
        ),
    ]
