# Generated by Django 5.0.7 on 2024-07-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_change_order_order_source_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Карта'), ('cash', 'Наличные'), ('online', 'Онлайн')], default='card', max_length=255, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_bonus_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общая сумма бонусов'),
        ),
    ]
