# Generated by Django 5.0.7 on 2024-07-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_excluded_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_percent', models.IntegerField(verbose_name='Процент за мобильное приложение')),
                ('web_percent', models.IntegerField(verbose_name='Процент за веб-сайт')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
