# Generated by Django 5.0.7 on 2024-07-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_change_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
