# Generated by Django 5.0.7 on 2024-07-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_percentcashback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/')),
                ('description', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='telegrambottoken',
            name='report_channels',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
