# Generated by Django 5.0.7 on 2024-07-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_restaurant_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Токен бота Telegram',
                'verbose_name_plural': 'Токены бота Telegram',
            },
        ),
    ]
