# Generated by Django 5.0.7 on 2024-07-17 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_telegrambottoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='telegram_chat_id',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='telegram_chat_ids',
            field=models.TextField(blank=True, help_text='Введите чат-айди через запятую', null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Telegram Chat IDs'),
        ),
    ]
