# Generated by Django 5.0.7 on 2024-07-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_report_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distancepricing',
            options={'verbose_name': 'Тариф на расстояние', 'verbose_name_plural': 'Тарифы на расстояния'},
        ),
        migrations.AlterModelOptions(
            name='percentcashback',
            options={'verbose_name': 'Процент кэшбэка', 'verbose_name_plural': 'Проценты кэшбэка'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='self_pickup_available',
            field=models.BooleanField(default=False, verbose_name='Самовывоз доступен'),
        ),
        migrations.AlterField(
            model_name='report',
            name='contact_number',
            field=models.CharField(max_length=15, verbose_name='Контактный номер'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='telegrambottoken',
            name='bot_token',
            field=models.CharField(max_length=200, unique=True, verbose_name='Телеграм Бот Токен'),
        ),
        migrations.AlterField(
            model_name='telegrambottoken',
            name='report_channels',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Айди каналов'),
        ),
    ]
