# Generated by Django 5.0.7 on 2024-07-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_restaurant_telegram_chat_id_and_more'),
    ]

    operations = [

    ]
