# Generated by Django 5.0.7 on 2024-07-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_restaurant_closing_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='self_pickup_available',
            field=models.BooleanField(default=True, verbose_name='Самовывоз доступен'),
        ),
    ]
