# Generated by Django 5.0.7 on 2024-07-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_change_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сдача'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Карта'), ('cash', 'Наличные'), ('online', 'Онлайн')], default='card', max_length=255, verbose_name='Способ оплаты'),
        ),
    ]
