# Generated by Django 5.0.7 on 2024-07-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_restaurant_self_pickup_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='set',
        ),
    ]
