# Generated by Django 5.0.7 on 2024-07-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_delivery_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='excluded_ingredient',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
