# Generated by Django 5.0.7 on 2024-07-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_orderitem_excluded_ingredient_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambottoken',
            name='app_download_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на приложение'),
        ),
    ]
