# Generated by Django 5.0.7 on 2024-08-05 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_useraddress_city'),
        ('orders', '0013_telegrambottoken_google_map_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.useraddress', verbose_name='Адрес пользователя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.delivery', verbose_name='Доставка'),
        ),
    ]
