# Generated by Django 5.0.7 on 2024-08-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='distance_km',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Расстояние (км)'),
        ),
    ]
