# Generated by Django 5.0.7 on 2024-08-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_delivery_distance_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(max_length=200, unique=True, verbose_name='Телеграм Бот Токен')),
            ],
            options={
                'verbose_name': 'Номер WhatsApp',
                'verbose_name_plural': 'Номер WhatsApp',
            },
        ),
    ]
