# Generated by Django 5.0.7 on 2024-08-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_whatsappchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='distance_km',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Расстояние (км)'),
        ),
    ]
