# Generated by Django 5.0.7 on 2024-10-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinOrderAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная сумма заказа')),
            ],
            options={
                'verbose_name': 'Минимальная сумма заказа',
                'verbose_name_plural': 'Минимальные суммы заказов',
            },
        ),
    ]
