# Generated by Django 5.0.7 on 2024-07-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.topping', verbose_name='Добавки'),
        ),
    ]
