# Generated by Django 5.0.7 on 2024-07-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_topping_bonuses_productsize_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='bonus_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена бонусами'),
        ),
        migrations.AddField(
            model_name='set',
            name='bonus_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена бонусами'),
        ),
    ]
