# Generated by Django 5.0.7 on 2024-07-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='set',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='set',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='set',
            name='name_ru',
        ),
    ]
