# Generated by Django 5.0.7 on 2024-07-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_set_description_ky_remove_set_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('text_color', models.CharField(max_length=100, verbose_name='Цвет текста')),
                ('background_color', models.CharField(max_length=100, verbose_name='Цвет фона')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.tag', verbose_name='Теги'),
        ),
    ]
