# Generated by Django 5.0.7 on 2024-07-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_tag_name_ky_tag_name_ru_alter_tag_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='product_photos/', verbose_name='Фото'),
        ),
    ]
