# Generated by Django 5.0.7 on 2024-07-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='title',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='icon',
            field=models.ImageField(default=1, help_text='Иконка для главной страницы.', upload_to='images/icons', verbose_name='Иконка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='phone',
            field=models.CharField(default=1, help_text='Контактный телефон для главной страницы.', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
