# Generated by Django 5.0.7 on 2024-07-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryconditions',
            options={'verbose_name': 'Условия доставки', 'verbose_name_plural': 'Условия доставки'},
        ),
        migrations.AlterModelOptions(
            name='methodsofpayment',
            options={'verbose_name': 'Способ оплаты', 'verbose_name_plural': 'Способы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='ordertypes',
            options={'verbose_name': 'Тип заказа', 'verbose_name_plural': 'Типы заказа'},
        ),
    ]
