# Generated by Django 5.0.7 on 2024-07-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_deliveryconditions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertypes',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_types', to='pages.mainpage'),
        ),
    ]
