# Generated by Django 5.0.7 on 2024-07-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_ordertypes_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/static', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_image',
            field=models.FileField(blank=True, null=True, upload_to='images/meta', verbose_name='Мета изображение'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
