# Generated by Django 5.0.7 on 2024-08-14 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_staticpage_image_alter_staticpage_meta_image_and_more'),
        ('product', '0009_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='banner',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('category', 'Категория'), ('product', 'Продукт'), ('link', 'Отдельная ссылка')], default='product', max_length=10, verbose_name='Тип баннера'),
        ),
    ]
