# Generated by Django 5.0.7 on 2024-08-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_banner_category_banner_product_banner_type'),
        ('product', '0010_product_is_new_product_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=123, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stories', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Группа историй',
                'verbose_name_plural': 'Группы историй',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stories', verbose_name='Изображение')),
                ('type', models.CharField(choices=[('category', 'Категория'), ('product', 'Продукт'), ('link', 'Отдельная ссылка')], default='product', max_length=10, verbose_name='Тип баннера')),
                ('link', models.URLField(blank=True, null=True, verbose_name='ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категория')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
                ('stories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.stories')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
    ]
