# Generated by Django 5.0.7 on 2024-08-30 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_stories_is_active_alter_story_stories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoriesUserCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('stories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_user_check', to='pages.stories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_user_check', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
