# Generated by Django 5.0.7 on 2024-09-23 09:14

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_storiesusercheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_app_image', models.FileField(blank=True, null=True, upload_to='bonus_pages', verbose_name='Мобильное приложение')),
                ('mobile_app_text', models.TextField(blank=True, null=True, verbose_name='Текст приложения')),
                ('mobile_app_color', colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет карточки приложения')),
                ('bonus_image', models.FileField(blank=True, null=True, upload_to='bonus_pages', verbose_name='Картинка карточки бонусов')),
                ('bonus_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок карточки бонусов')),
                ('bonus_text', models.TextField(blank=True, null=True, verbose_name='Текст карточки бонусов')),
                ('bonus_color', colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет карточки бонусов')),
                ('bottom_card_text', models.TextField(blank=True, null=True, verbose_name='Нижняя часть карточки')),
                ('bottom_cart_color', colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет нижней части карточки')),
            ],
            options={
                'verbose_name': 'Бонусная страница',
                'verbose_name_plural': 'Бонусная страница',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('site_description', models.TextField(verbose_name='Описание сайта')),
                ('site_logo', models.FileField(blank=True, null=True, upload_to='site_logos', verbose_name='Логотип сайта')),
                ('site_bottom_logo', models.FileField(blank=True, null=True, upload_to='site_logos', verbose_name='Логотип нижней части сайта')),
                ('site_favicon', models.FileField(blank=True, null=True, upload_to='site_favicons', verbose_name='Иконка сайта')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
