# Generated by Django 5.0.7 on 2024-07-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_useraddress_city_alter_useraddress_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='street',
        ),
    ]
