# Generated by Django 5.0.7 on 2024-07-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_useraddress_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес'),
        ),
    ]
