# Generated by Django 5.0.7 on 2024-09-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_useraddress_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=200, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=200, null=True, verbose_name='Долгота'),
        ),
    ]
