# Generated by Django 5.0.7 on 2024-09-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_useraddress_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True, verbose_name='Долгота'),
        ),
    ]
