# Generated by Django 5.0.7 on 2024-09-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_admin_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
